"""P37 — AI Summary & Health Score API Response Audit

Verifies that AI summary, health score, and AI module API routes do not expose
user_id or any sensitive/internal fields to client responses, and that
cross-user person_id access returns 404.

ORM surface audited:
  AISummary.user_id      — in DB column, NOT in AISummaryResponse schema
  HealthScore.user_id    — in DB column, NOT in HealthScoreResponse schema

Routes covered
--------------
AI Summary:
  POST /ai-summary/generate        → AISummaryResponse (response_model enforced)
  GET  /ai-summary                 → list[AISummaryResponse] (response_model enforced)

Health Score:
  POST /health-score/calculate     → HealthScoreResponse (response_model enforced)
  GET  /health-score/latest        → Optional[HealthScoreResponse] (response_model enforced)
  GET  /health-score/history       → list[HealthScoreResponse] (response_model enforced)

Coverage map
------------
TestAISummaryResponseLeakage
  test_generate_summary_no_user_id       → POST generate: user_id absent
  test_generate_summary_no_sensitive_keys → POST generate: recursive scan
  test_list_summary_no_user_id           → GET list: user_id absent
  test_list_summary_no_sensitive_keys    → GET list: recursive scan
  test_generate_summary_field_contract   → declared public fields present; user_id absent

TestHealthScoreResponseLeakage
  test_calculate_score_no_user_id        → POST calculate: user_id absent
  test_calculate_score_no_sensitive_keys → POST calculate: recursive scan (includes score_detail)
  test_latest_score_no_user_id           → GET latest: user_id absent
  test_latest_score_no_sensitive_keys    → GET latest: recursive scan
  test_history_score_no_user_id          → GET history: user_id absent
  test_history_score_no_sensitive_keys   → GET history: recursive scan

TestCrossUserAIHealthIsolation
  test_cross_user_ai_summary_404         → foreign person_id on GET /ai-summary → 404
  test_cross_user_health_score_404       → foreign person_id on GET /health-score/latest → 404

Audit Result:
  No C.GAP found.
  AISummaryResponse: A.SAFE (user_id ORM column not declared in schema;
                              from_attributes only serializes declared fields)
  HealthScoreResponse: A.SAFE (same pattern)
  AIModuleResponse / AIModuleEvaluationResponse: A.SAFE (no ORM, pure
                              structured AI output, no user_id in schema)
  narrative_json: A.SAFE (generated by ai_service which returns only
                              summary_text/disclaimer/model_name — no user_id)
  score_detail: A.SAFE (health metrics and scoring penalties only — no user_id)
"""
from __future__ import annotations

import uuid
from datetime import date, datetime, timezone
from typing import Any
from unittest.mock import patch

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker
from sqlalchemy.pool import StaticPool

from app.core.database import Base, get_db
from app.core.deps import get_current_user
from app.main import app
from app.models.entities import AISummary, HealthScore, PersonProfile, User


# ---------------------------------------------------------------------------
# Sensitive key set — same as P32–P36 regression suites
# ---------------------------------------------------------------------------

_SENSITIVE_KEYS: frozenset[str] = frozenset({
    "password_hash",
    "hashed_password",
    "password",
    "storage_bucket",
    "storage_key",
    "file_path",
    "download_token",
    "secret_key",
    "secret",
    "is_superuser",
    "is_staff",
    "user_id",
})


def _find_sensitive_key(obj: Any, path: str = "") -> str | None:
    """Recursively scan a deserialized JSON object for sensitive key names.

    Returns the first offending key path, or None if clean.
    """
    if isinstance(obj, dict):
        for k, v in obj.items():
            if k.lower() in _SENSITIVE_KEYS:
                return f"{path}.{k}" if path else k
            found = _find_sensitive_key(v, f"{path}.{k}" if path else k)
            if found:
                return found
    elif isinstance(obj, list):
        for i, item in enumerate(obj):
            found = _find_sensitive_key(item, f"{path}[{i}]")
            if found:
                return found
    return None


# ---------------------------------------------------------------------------
# Shared DB + user helpers
# ---------------------------------------------------------------------------


@pytest.fixture(autouse=True)
def _clear_overrides():
    yield
    app.dependency_overrides.clear()


def _make_db_and_user(email: str = "p37test@example.com") -> tuple[Session, User, PersonProfile]:
    engine = create_engine(
        "sqlite://",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    SLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    Base.metadata.create_all(bind=engine)
    db: Session = SLocal()

    user = User(
        id=uuid.uuid4(),
        email=email,
        password_hash="hashed_not_real",
        is_active=True,
    )
    db.add(user)
    db.flush()

    person = PersonProfile(
        id=uuid.uuid4(),
        owner_user_id=user.id,
        display_name="P37 Test User",
        relationship="self",
        is_default=True,
    )
    db.add(person)
    db.commit()
    return db, user, person


def _make_client(db: Session, user: User) -> TestClient:
    app.dependency_overrides[get_db] = lambda: db
    app.dependency_overrides[get_current_user] = lambda: user
    return TestClient(app, raise_server_exceptions=False)


# ---------------------------------------------------------------------------
# Seed helpers
# ---------------------------------------------------------------------------


def _seed_ai_summary(db: Session, user: User, person: PersonProfile) -> AISummary:
    """Seed an AISummary ORM record directly (bypasses OpenAI call).

    user_id is an ORM internal field — must NOT appear in AISummaryResponse.
    """
    summary = AISummary(
        id=uuid.uuid4(),
        user_id=user.id,              # UUID object — correct
        subject_profile_id=person.id,
        period_start=date.today(),
        period_end=date.today(),
        summary_text="血壓和血糖數值穩定，繼續保持良好生活習慣。",
        abnormal_explanation="無明顯異常值。",
        recommendations="建議規律運動，均衡飲食。",
        disclaimer="本資訊僅供參考，不構成醫療建議。",
        model_name="rule-based-fallback",
    )
    db.add(summary)
    db.commit()
    db.refresh(summary)
    return summary


def _seed_health_score(db: Session, user: User, person: PersonProfile) -> HealthScore:
    """Seed a HealthScore ORM record directly (bypasses scoring engine).

    user_id is an ORM internal field — must NOT appear in HealthScoreResponse.
    """
    score = HealthScore(
        id=uuid.uuid4(),
        user_id=user.id,               # UUID object — correct
        subject_profile_id=person.id,
        source_period_days=30,
        overall_score=82,
        cardiovascular_score=88,
        metabolic_score=79,
        weight_score=90,
        sleep_score=75,
        score_detail={
            "cardiovascular": {"score": 88, "avg_systolic": 115.0, "avg_diastolic": 72.0},
            "metabolic": {"score": 79, "avg_glucose": 96.0},
            "weight": {"score": 90, "bmi": 22.1},
            "activity": {"score": 75, "avg_sleep_hours": 7.2},
            "rule_penalties": {},
            "applied_rules": [],
        },
    )
    db.add(score)
    db.commit()
    db.refresh(score)
    return score


# ---------------------------------------------------------------------------
# Mock return values for POST endpoints that call external services
# ---------------------------------------------------------------------------

_MOCK_SUMMARY_RETURN = {
    "period_start": date.today(),
    "period_end": date.today(),
    "summary_text": "健康狀況良好。",
    "abnormal_explanation": "無異常。",
    "recommendations": "請維持良好生活習慣。",
    "disclaimer": "本資訊僅供參考，不構成醫療建議。",
    "model_name": "rule-based-fallback",
}

_MOCK_SCORE_RETURN = {
    "source_period_days": 30,
    "overall_score": 80,
    "cardiovascular_score": 85,
    "metabolic_score": 75,
    "weight_score": 90,
    "sleep_score": 78,
    "score_detail": {
        "cardiovascular": {"score": 85, "avg_systolic": 118.0, "avg_diastolic": 75.0},
        "metabolic": {"score": 75, "avg_glucose": 95.0},
        "weight": {"score": 90, "bmi": 22.5},
        "activity": {"score": 78, "avg_sleep_hours": 7.5},
        "rule_penalties": {},
        "applied_rules": [],
    },
}


# ---------------------------------------------------------------------------
# TestAISummaryResponseLeakage
# ---------------------------------------------------------------------------


class TestAISummaryResponseLeakage:
    """AI summary routes must not expose user_id or sensitive fields."""

    def test_generate_summary_no_user_id(self):
        """POST /ai-summary/generate response must not contain user_id."""
        db, user, person = _make_db_and_user()
        client = _make_client(db, user)
        with patch("app.api.ai_summary.generate_health_summary", return_value=_MOCK_SUMMARY_RETURN):
            resp = client.post(
                "/api/v1/ai-summary/generate",
                json={"period_start": str(date.today()), "period_end": str(date.today())},
                params={"person_id": str(person.id)},
            )
        assert resp.status_code == 200, resp.text
        body = resp.json()
        assert "user_id" not in body, (
            f"AISummaryResponse must not expose user_id. Got keys: {list(body.keys())}"
        )

    def test_generate_summary_no_sensitive_keys(self):
        """POST /ai-summary/generate response must pass recursive sensitive-key scan."""
        db, user, person = _make_db_and_user()
        client = _make_client(db, user)
        with patch("app.api.ai_summary.generate_health_summary", return_value=_MOCK_SUMMARY_RETURN):
            resp = client.post(
                "/api/v1/ai-summary/generate",
                json={"period_start": str(date.today()), "period_end": str(date.today())},
                params={"person_id": str(person.id)},
            )
        assert resp.status_code == 200, resp.text
        found = _find_sensitive_key(resp.json())
        assert found is None, (
            f"Sensitive key '{found}' found in POST /ai-summary/generate response."
        )

    def test_list_summary_no_user_id(self):
        """GET /ai-summary list items must not contain user_id."""
        db, user, person = _make_db_and_user()
        _seed_ai_summary(db, user, person)
        client = _make_client(db, user)
        resp = client.get("/api/v1/ai-summary", params={"person_id": str(person.id)})
        assert resp.status_code == 200, resp.text
        items = resp.json()
        assert isinstance(items, list)
        assert len(items) >= 1
        for item in items:
            assert "user_id" not in item, (
                f"AISummaryResponse must not expose user_id. Got keys: {list(item.keys())}"
            )

    def test_list_summary_no_sensitive_keys(self):
        """GET /ai-summary response must pass recursive sensitive-key scan."""
        db, user, person = _make_db_and_user()
        _seed_ai_summary(db, user, person)
        client = _make_client(db, user)
        resp = client.get("/api/v1/ai-summary", params={"person_id": str(person.id)})
        assert resp.status_code == 200, resp.text
        found = _find_sensitive_key(resp.json())
        assert found is None, (
            f"Sensitive key '{found}' found in GET /ai-summary response."
        )

    def test_generate_summary_field_contract(self):
        """AISummaryResponse must expose intended public fields and not expose user_id/subject_profile_id."""
        db, user, person = _make_db_and_user()
        client = _make_client(db, user)
        with patch("app.api.ai_summary.generate_health_summary", return_value=_MOCK_SUMMARY_RETURN):
            resp = client.post(
                "/api/v1/ai-summary/generate",
                json={"period_start": str(date.today()), "period_end": str(date.today())},
                params={"person_id": str(person.id)},
            )
        assert resp.status_code == 200, resp.text
        body = resp.json()
        # Public fields that MUST be present
        assert "id" in body, "AISummaryResponse must include 'id'"
        assert "summary_text" in body, "AISummaryResponse must include 'summary_text'"
        assert "disclaimer" in body, "AISummaryResponse must include 'disclaimer'"
        assert "created_at" in body, "AISummaryResponse must include 'created_at'"
        # ORM internal fields that must NOT be present
        assert "user_id" not in body, "AISummaryResponse must NOT expose 'user_id'"
        assert "subject_profile_id" not in body, (
            "AISummaryResponse must NOT expose 'subject_profile_id'"
        )


# ---------------------------------------------------------------------------
# TestHealthScoreResponseLeakage
# ---------------------------------------------------------------------------


class TestHealthScoreResponseLeakage:
    """Health score routes must not expose user_id or sensitive fields.

    score_detail is a JSON blob containing health metrics and scoring details.
    Each sub-dict (cardiovascular, metabolic, weight, activity) is scanned
    recursively to verify no user_id or internal fields leak through.
    """

    def test_calculate_score_no_user_id(self):
        """POST /health-score/calculate response must not contain user_id."""
        db, user, person = _make_db_and_user()
        client = _make_client(db, user)
        with patch("app.api.health_score.calculate_health_score", return_value=_MOCK_SCORE_RETURN):
            resp = client.post(
                "/api/v1/health-score/calculate",
                json={"days": 30},
                params={"person_id": str(person.id)},
            )
        assert resp.status_code == 200, resp.text
        body = resp.json()
        assert "user_id" not in body, (
            f"HealthScoreResponse must not expose user_id. Got keys: {list(body.keys())}"
        )

    def test_calculate_score_no_sensitive_keys(self):
        """POST /health-score/calculate response must pass recursive scan (includes score_detail)."""
        db, user, person = _make_db_and_user()
        client = _make_client(db, user)
        with patch("app.api.health_score.calculate_health_score", return_value=_MOCK_SCORE_RETURN):
            resp = client.post(
                "/api/v1/health-score/calculate",
                json={"days": 30},
                params={"person_id": str(person.id)},
            )
        assert resp.status_code == 200, resp.text
        found = _find_sensitive_key(resp.json())
        assert found is None, (
            f"Sensitive key '{found}' found in POST /health-score/calculate response "
            f"(includes score_detail dict)."
        )

    def test_latest_score_no_user_id(self):
        """GET /health-score/latest response must not contain user_id."""
        db, user, person = _make_db_and_user()
        _seed_health_score(db, user, person)
        client = _make_client(db, user)
        resp = client.get("/api/v1/health-score/latest", params={"person_id": str(person.id)})
        assert resp.status_code == 200, resp.text
        body = resp.json()
        assert body is not None
        assert "user_id" not in body, (
            f"HealthScoreResponse must not expose user_id. Got keys: {list(body.keys())}"
        )

    def test_latest_score_no_sensitive_keys(self):
        """GET /health-score/latest response must pass recursive scan (includes score_detail)."""
        db, user, person = _make_db_and_user()
        _seed_health_score(db, user, person)
        client = _make_client(db, user)
        resp = client.get("/api/v1/health-score/latest", params={"person_id": str(person.id)})
        assert resp.status_code == 200, resp.text
        found = _find_sensitive_key(resp.json())
        assert found is None, (
            f"Sensitive key '{found}' found in GET /health-score/latest response "
            f"(includes score_detail dict)."
        )

    def test_history_score_no_user_id(self):
        """GET /health-score/history list items must not contain user_id."""
        db, user, person = _make_db_and_user()
        _seed_health_score(db, user, person)
        client = _make_client(db, user)
        resp = client.get("/api/v1/health-score/history", params={"person_id": str(person.id)})
        assert resp.status_code == 200, resp.text
        items = resp.json()
        assert isinstance(items, list)
        assert len(items) >= 1
        for item in items:
            assert "user_id" not in item, (
                f"HealthScoreResponse must not expose user_id. Got keys: {list(item.keys())}"
            )

    def test_history_score_no_sensitive_keys(self):
        """GET /health-score/history response must pass recursive scan."""
        db, user, person = _make_db_and_user()
        _seed_health_score(db, user, person)
        client = _make_client(db, user)
        resp = client.get("/api/v1/health-score/history", params={"person_id": str(person.id)})
        assert resp.status_code == 200, resp.text
        found = _find_sensitive_key(resp.json())
        assert found is None, (
            f"Sensitive key '{found}' found in GET /health-score/history response."
        )


# ---------------------------------------------------------------------------
# TestCrossUserAIHealthIsolation
# ---------------------------------------------------------------------------


class TestCrossUserAIHealthIsolation:
    """Cross-user person_id on AI/health-score routes must return 404."""

    def test_cross_user_ai_summary_404(self):
        """GET /ai-summary with a foreign person_id must return 404."""
        db, user_a, _ = _make_db_and_user("p37a@example.com")

        user_b = User(
            id=uuid.uuid4(),
            email="p37b@example.com",
            password_hash="hashed_not_real",
            is_active=True,
        )
        db.add(user_b)
        db.flush()
        person_b = PersonProfile(
            id=uuid.uuid4(),
            owner_user_id=user_b.id,
            display_name="User B",
            relationship="self",
            is_default=True,
        )
        db.add(person_b)
        db.commit()

        # user_a authenticates but targets user_b's person_id
        client = _make_client(db, user_a)
        resp = client.get("/api/v1/ai-summary", params={"person_id": str(person_b.id)})
        assert resp.status_code == 404, (
            f"Expected 404 for foreign person_id on GET /ai-summary, got {resp.status_code}"
        )

    def test_cross_user_health_score_404(self):
        """GET /health-score/latest with a foreign person_id must return 404."""
        db, user_a, _ = _make_db_and_user("p37c@example.com")

        user_b = User(
            id=uuid.uuid4(),
            email="p37d@example.com",
            password_hash="hashed_not_real",
            is_active=True,
        )
        db.add(user_b)
        db.flush()
        person_b = PersonProfile(
            id=uuid.uuid4(),
            owner_user_id=user_b.id,
            display_name="User B",
            relationship="self",
            is_default=True,
        )
        db.add(person_b)
        db.commit()

        client = _make_client(db, user_a)
        resp = client.get(
            "/api/v1/health-score/latest", params={"person_id": str(person_b.id)}
        )
        assert resp.status_code == 404, (
            f"Expected 404 for foreign person_id on GET /health-score/latest, "
            f"got {resp.status_code}"
        )
