"""P18 — Report Authorization Hardening Regression

Verifies that the report status endpoint enforces report ownership so that
user B cannot query or receive the download URL for a report generated by
user A.

Mechanism under test
--------------------
``_REPORT_STATE`` (in-memory dict, app/api/reports.py) now stores
``owner_user_id = str(current_user.id)`` for every generated report.

``GET /api/v1/reports/{report_id}`` (get_report_status) now checks:
    str(state['owner_user_id']) != str(current_user.id)  →  HTTP 404

``GET /api/v1/reports/download/{report_id}?token=...`` remains token-only
(no JWT auth) — this is the documented DOWNLOAD_GAP.  The token is only
ever returned to the report owner through the hardened status endpoint, so
in practice the download URL is not obtainable by another user without the
status endpoint leaking it.

Coverage
--------
TestReportStatusAuthHardened
  test_status_own_report_ok               → 200, status ready
  test_status_cross_user_denied           → 404 (no data leak)
  test_status_unknown_report_denied       → 404
  test_status_response_no_leak            → body must not contain owner's id

TestReportGenerateOwnerBinding
  test_generate_sets_owner_user_id        → _REPORT_STATE contains owner_user_id

TestReportDownloadTokenOnly
  test_download_valid_token_ok            → 200 (owner uses correct token)
  test_download_wrong_token_denied        → 403
  test_download_unknown_report_denied     → 404

Strategy: SQLite in-memory DB + get_db override + get_current_user override.
get_target_person is NOT overridden — production ownership code runs unchanged.
_REPORT_STATE is cleared before and after each test to prevent state leakage.
"""
from __future__ import annotations

import uuid

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker
from sqlalchemy.pool import StaticPool

from app.api.reports import _REPORT_STATE
from app.core.database import Base, get_db
from app.core.deps import get_current_user
from app.main import app
from app.models.entities import PersonProfile, User


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(autouse=True)
def _clear_app_overrides_and_report_state():
    """Isolate each test: wipe dependency overrides + in-memory report state."""
    _REPORT_STATE.clear()
    yield
    app.dependency_overrides.clear()
    _REPORT_STATE.clear()


def _build_two_user_db() -> tuple[Session, User, PersonProfile, User, PersonProfile]:
    """Create two users each owning one PersonProfile in a fresh SQLite DB.

    Returns (db, user_a, person_a, user_b, person_b).
    """
    engine = create_engine(
        "sqlite://",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    SLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    Base.metadata.create_all(bind=engine)
    db: Session = SLocal()

    user_a = User(email=f"p18_a_{uuid.uuid4().hex[:8]}@example.com", password_hash="h")
    user_b = User(email=f"p18_b_{uuid.uuid4().hex[:8]}@example.com", password_hash="h")
    db.add_all([user_a, user_b])
    db.commit()
    db.refresh(user_a)
    db.refresh(user_b)

    person_a = PersonProfile(
        owner_user_id=user_a.id,
        display_name="P18 User A Self",
        relationship="self",
        is_default=True,
    )
    person_b = PersonProfile(
        owner_user_id=user_b.id,
        display_name="P18 User B Self",
        relationship="self",
        is_default=True,
    )
    db.add_all([person_a, person_b])
    db.commit()
    db.refresh(person_a)
    db.refresh(person_b)

    return db, user_a, person_a, user_b, person_b


def _set_user(db: Session, user: User) -> TestClient:
    """Switch dependency overrides to the given user and return a TestClient."""
    def _override_db():
        yield db

    app.dependency_overrides[get_db] = _override_db
    app.dependency_overrides[get_current_user] = lambda: user
    return TestClient(app)


# ---------------------------------------------------------------------------
# TestReportGenerateOwnerBinding
# ---------------------------------------------------------------------------


class TestReportGenerateOwnerBinding:
    """Verifies that generate_report stores owner_user_id in _REPORT_STATE."""

    def test_generate_sets_owner_user_id(self):
        db, user_a, person_a, _user_b, _person_b = _build_two_user_db()
        client = _set_user(db, user_a)

        resp = client.post('/api/v1/reports/generate', json={})
        assert resp.status_code == 202, f"Expected 202, got {resp.status_code}: {resp.text}"

        report_id = resp.json()['report_id']
        state = _REPORT_STATE.get(report_id)
        assert state is not None, "Report state not found in _REPORT_STATE"
        assert 'owner_user_id' in state, "_REPORT_STATE entry missing owner_user_id"
        assert state['owner_user_id'] == str(user_a.id), (
            f"Expected owner_user_id={user_a.id}, got {state['owner_user_id']}"
        )


# ---------------------------------------------------------------------------
# TestReportStatusAuthHardened
# ---------------------------------------------------------------------------


class TestReportStatusAuthHardened:
    """GET /api/v1/reports/{report_id} must enforce ownership.

    user_a generates a report.  user_b must not be able to query its status
    or receive the download URL.
    """

    def _generate_as_user_a(self) -> tuple[Session, User, User, str, str]:
        """Generate a report as user_a; return (db, user_a, user_b, report_id, token)."""
        db, user_a, _person_a, user_b, _person_b = _build_two_user_db()
        client_a = _set_user(db, user_a)

        resp = client_a.post('/api/v1/reports/generate', json={})
        assert resp.status_code == 202, f"Generate failed: {resp.text}"
        report_id = resp.json()['report_id']
        token = _REPORT_STATE[report_id]['token']
        return db, user_a, user_b, report_id, token

    def test_status_own_report_ok(self):
        db, user_a, _user_b, report_id, _token = self._generate_as_user_a()
        client_a = _set_user(db, user_a)

        resp = client_a.get(f'/api/v1/reports/{report_id}')
        assert resp.status_code == 200, f"Owner should see own report, got {resp.status_code}: {resp.text}"
        data = resp.json()
        assert data['status'] == 'ready', f"Expected ready, got {data['status']}"
        assert data.get('download_url') is not None, "Owner should receive download_url"

    def test_status_cross_user_denied(self):
        db, user_a, user_b, report_id, _token = self._generate_as_user_a()
        client_b = _set_user(db, user_b)

        resp = client_b.get(f'/api/v1/reports/{report_id}')
        assert resp.status_code == 404, (
            f"Cross-user report status: expected 404, got {resp.status_code}. Body: {resp.text}"
        )

    def test_status_unknown_report_denied(self):
        db, user_a, _user_b, _report_id, _token = self._generate_as_user_a()
        client_a = _set_user(db, user_a)

        fake_id = str(uuid.uuid4())
        resp = client_a.get(f'/api/v1/reports/{fake_id}')
        assert resp.status_code == 404, (
            f"Unknown report_id: expected 404, got {resp.status_code}. Body: {resp.text}"
        )

    def test_status_response_no_leak(self):
        """The 404 response body must not contain user_a's report_id or token."""
        db, user_a, user_b, report_id, token = self._generate_as_user_a()
        client_b = _set_user(db, user_b)

        resp = client_b.get(f'/api/v1/reports/{report_id}')
        assert resp.status_code == 404
        body = resp.text
        assert report_id not in body, "404 body must not echo the report_id"
        assert token not in body, "404 body must not leak the download token"
        assert str(user_a.id) not in body, "404 body must not leak user_a.id"


# ---------------------------------------------------------------------------
# TestReportDownloadTokenOnly
# ---------------------------------------------------------------------------


class TestReportDownloadTokenOnly:
    """GET /api/v1/reports/download/{report_id}?token=...

    The download endpoint is token-only (no JWT auth).  The token is a UUID
    secret only obtainable via the hardened status endpoint (which now denies
    cross-user access).  Tests here verify the token-validation logic.

    Known gap: if the token leaks via other means (browser history, network
    capture), a third party can download.  This is the documented DOWNLOAD_GAP
    and is acceptable given the 1-hour expiry and unguessable UUID token.
    """

    def _generate_as_user_a(self) -> tuple[Session, User, User, str, str]:
        db, user_a, _person_a, user_b, _person_b = _build_two_user_db()
        client_a = _set_user(db, user_a)

        resp = client_a.post('/api/v1/reports/generate', json={})
        assert resp.status_code == 202
        report_id = resp.json()['report_id']
        token = _REPORT_STATE[report_id]['token']
        return db, user_a, user_b, report_id, token

    def test_download_valid_token_ok(self):
        """Owner uses the token obtained via status → download succeeds."""
        db, user_a, _user_b, report_id, token = self._generate_as_user_a()
        # download endpoint has no JWT: token is the sole credential
        client_a = _set_user(db, user_a)

        resp = client_a.get(f'/api/v1/reports/download/{report_id}', params={'token': token})
        assert resp.status_code == 200, (
            f"Valid token download failed: {resp.status_code}: {resp.text}"
        )
        assert resp.headers.get('content-type', '').startswith('application/pdf'), (
            f"Expected PDF content-type, got {resp.headers.get('content-type')}"
        )

    def test_download_wrong_token_denied(self):
        """Correct report_id but wrong token → 403."""
        db, user_a, _user_b, report_id, _token = self._generate_as_user_a()
        client_a = _set_user(db, user_a)

        wrong_token = str(uuid.uuid4())
        resp = client_a.get(f'/api/v1/reports/download/{report_id}', params={'token': wrong_token})
        assert resp.status_code == 403, (
            f"Wrong token: expected 403, got {resp.status_code}. Body: {resp.text}"
        )

    def test_download_unknown_report_denied(self):
        """Unknown report_id → 404."""
        db, user_a, _user_b, _report_id, _token = self._generate_as_user_a()
        client_a = _set_user(db, user_a)

        fake_id = str(uuid.uuid4())
        resp = client_a.get(f'/api/v1/reports/download/{fake_id}', params={'token': 'any'})
        assert resp.status_code == 404, (
            f"Unknown report_id: expected 404, got {resp.status_code}. Body: {resp.text}"
        )
